---
title: "pivot"
author: "gokul"
date: "2024-05-02"
output: html_document
---

```{r}
## attach libraries
library(tidyverse)
library(readxl)
library(here)
library(skimr) # install.packages('skimr')
library(kableExtra) # install.packages('kableExtra')


lobsters <- read_xlsx(here("data/lobsters.xlsx"), skip = 4)
head(lobsters)

skimr:: skim(lobsters)


lobsters %>%
group_by(year) %>%
summarize(count_by_year = n())


lobsters %>%
summarize(count = n())


lobsters %>%
group_by(year)


lobsters %>%
group_by(site, year) %>%
summarize(count_by_year = n())

lobsters %>%
group_by(site, year) %>%
summarize(count_by_siteyear = n(),
mean_size_mm = mean(size_mm))



lobsters %>%
group_by(site, year) %>%
summarize(count_by_year = n(), 
mean_size_mm = mean(size_mm, na.rm = TRUE), 
sd_size_mm = sd(size_mm, na.rm = TRUE))


siteyear_summary <- lobsters %>%
group_by(site, year) %>%
summarize(count_by_year = n(), 
mean_size_mm = mean(size_mm, na.rm = TRUE), 
sd_size_mm = sd(size_mm, na.rm = TRUE))



siteyear_summary

siteyear_summary %>%
kable()




```

there are `r nrow(lobsters)` total lobsters included in this report

```{r}
lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_site = n(), median_size_mm = median(size_mm, na.rm = TRUE))
```

for_plotting <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_site = n(), median_size_mm = median(size_mm, na.rm = TRUE))

ggplot(data = for_plotting, aes(x= year , y = median_size_mm, color = site)) + geom_col()

```{r}

for_plotting <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_site = n(), median_size_mm = median(size_mm, na.rm = TRUE))

ggplot(data = for_plotting, aes(x= year , y = median_size_mm, color = site)) + geom_col() + facet_wrap(~site)
```
ggsave(here("figures","lobsters.jpg"), dpi = 800)
